/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "AliveRow",
  "description": "",
  "base": "/lib/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/lib/img/avatar.png"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "/lib/css/index.css"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/avatar.png",
        "heroText": "AliveRow",
        "tagline": "要一直学习,避免被淘汰",
        "actionLink": "/zh/guide/",
        "footer": "MIT Licensed | Copyright © 2018-present"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-10f277a5",
      "path": "/"
    },
    {
      "title": "面试相关",
      "frontmatter": {},
      "regularPath": "/interview/",
      "relativePath": "interview/README.md",
      "key": "v-47f7b87e",
      "path": "/interview/",
      "headers": [
        {
          "level": 2,
          "title": "symbol是什么基本数据类型还是引用数类型",
          "slug": "symbol是什么基本数据类型还是引用数类型"
        },
        {
          "level": 2,
          "title": "for in和for of的区别",
          "slug": "for-in和for-of的区别"
        },
        {
          "level": 2,
          "title": "那些方法改变原数组,哪些不会改变原数组",
          "slug": "那些方法改变原数组-哪些不会改变原数组"
        },
        {
          "level": 2,
          "title": "ES5和ES6的继承方式?",
          "slug": "es5和es6的继承方式"
        },
        {
          "level": 2,
          "title": "super方法的作用",
          "slug": "super方法的作用"
        },
        {
          "level": 2,
          "title": "TS的泛型",
          "slug": "ts的泛型"
        },
        {
          "level": 2,
          "title": "TS私有属性和受保护的数据的属性关键字",
          "slug": "ts私有属性和受保护的数据的属性关键字"
        },
        {
          "level": 2,
          "title": "Vue3和Vue2的区别",
          "slug": "vue3和vue2的区别"
        },
        {
          "level": 2,
          "title": "Mixin的原理",
          "slug": "mixin的原理"
        },
        {
          "level": 2,
          "title": "Es6",
          "slug": "es6"
        },
        {
          "level": 2,
          "title": "keep-alive的两个生命周期",
          "slug": "keep-alive的两个生命周期"
        },
        {
          "level": 2,
          "title": "轮播图组件思路",
          "slug": "轮播图组件思路"
        },
        {
          "level": 2,
          "title": "webpack多页面",
          "slug": "webpack多页面"
        },
        {
          "level": 2,
          "title": "将一个字符串反向",
          "slug": "将一个字符串反向"
        }
      ]
    },
    {
      "title": "每日整理",
      "frontmatter": {},
      "regularPath": "/daysort/",
      "relativePath": "daysort/README.md",
      "key": "v-2cb6bacf",
      "path": "/daysort/",
      "headers": [
        {
          "level": 2,
          "title": "2020",
          "slug": "_2020"
        },
        {
          "level": 3,
          "title": "10月",
          "slug": "_10月"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/notes/CSS/",
      "relativePath": "notes/CSS/README.md",
      "key": "v-2e0f8a99",
      "path": "/notes/CSS/"
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/notes/HTML/",
      "relativePath": "notes/HTML/README.md",
      "key": "v-2ca8c435",
      "path": "/notes/HTML/"
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/notes/JavaScript/",
      "relativePath": "notes/JavaScript/README.md",
      "key": "v-8f97f716",
      "path": "/notes/JavaScript/"
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/notes/Node/",
      "relativePath": "notes/Node/README.md",
      "key": "v-0c35cfd5",
      "path": "/notes/Node/"
    },
    {
      "title": "前言",
      "frontmatter": {},
      "regularPath": "/notes/",
      "relativePath": "notes/README.md",
      "key": "v-69b8a941",
      "path": "/notes/",
      "headers": [
        {
          "level": 2,
          "title": "前端网站收集",
          "slug": "前端网站收集"
        },
        {
          "level": 2,
          "title": "工具类",
          "slug": "工具类"
        }
      ]
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/notes/Vue/",
      "relativePath": "notes/Vue/README.md",
      "key": "v-3233c3d3",
      "path": "/notes/Vue/"
    },
    {
      "title": "HTML",
      "frontmatter": {},
      "regularPath": "/notes/Webpack/",
      "relativePath": "notes/Webpack/README.md",
      "key": "v-d47bb776",
      "path": "/notes/Webpack/"
    },
    {
      "title": "Snippets-CSS",
      "frontmatter": {},
      "regularPath": "/snippets/CSS/",
      "relativePath": "snippets/CSS/README.md",
      "key": "v-d59cdf56",
      "path": "/snippets/CSS/"
    },
    {
      "title": "Snippets-HTML",
      "frontmatter": {},
      "regularPath": "/snippets/HTML/",
      "relativePath": "snippets/HTML/README.md",
      "key": "v-ed686b8a",
      "path": "/snippets/HTML/"
    },
    {
      "title": "Snippets-JavaScript",
      "frontmatter": {},
      "regularPath": "/snippets/JavaScript/",
      "relativePath": "snippets/JavaScript/README.md",
      "key": "v-429869f7",
      "path": "/snippets/JavaScript/"
    },
    {
      "title": "Snippets-Node",
      "frontmatter": {},
      "regularPath": "/snippets/Node/",
      "relativePath": "snippets/Node/README.md",
      "key": "v-3c19b80d",
      "path": "/snippets/Node/"
    },
    {
      "title": "Snippets-Vue",
      "frontmatter": {},
      "regularPath": "/snippets/Vue/",
      "relativePath": "snippets/Vue/README.md",
      "key": "v-608167b5",
      "path": "/snippets/Vue/"
    },
    {
      "title": "Snippets-微信小程序",
      "frontmatter": {},
      "regularPath": "/snippets/WeChatApp/",
      "relativePath": "snippets/WeChatApp/README.md",
      "key": "v-e34c68d6",
      "path": "/snippets/WeChatApp/"
    }
  ],
  "themeConfig": {
    "logo": "/img/avatar.png",
    "smoothScroll": true,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端学习笔记",
        "link": "/notes/"
      },
      {
        "text": "每日整理",
        "link": "/daysort/"
      },
      {
        "text": "面试相关",
        "link": "/interview/"
      },
      {
        "text": "Snippets",
        "ariaLabel": "Snippets",
        "items": [
          {
            "text": "HTML",
            "link": "/snippets/HTML/"
          },
          {
            "text": "CSS",
            "link": "/snippets/CSS/"
          },
          {
            "text": "JavaScript",
            "link": "/snippets/JavaScript/"
          },
          {
            "text": "Vue",
            "link": "/snippets/Vue/"
          },
          {
            "text": "Node",
            "link": "/snippets/Node/"
          },
          {
            "text": "WeChatApp",
            "link": "/snippets/WeChatApp/"
          }
        ]
      },
      {
        "text": "个人项目",
        "items": [
          {
            "text": "AliveMusic",
            "link": "http://alivemusic.dreamsakula.top/"
          },
          {
            "text": "AliveNote",
            "link": "http://alivenote.dreamsakula.top/"
          },
          {
            "text": "GritUI",
            "link": "http://aliveui.dreamsakula.top/#/"
          }
        ]
      },
      {
        "text": "其他",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/AliveCrow"
          },
          {
            "text": "博客",
            "link": "https://dreamsakula.top/"
          },
          {
            "text": "TODO",
            "link": "/todo/"
          }
        ]
      }
    ],
    "sidebarDepth": 3,
    "sidebar": {
      "/notes/": [
        "/notes/",
        {
          "title": "HTML",
          "path": "/notes/HTML/"
        },
        {
          "title": "CSS",
          "path": "/notes/CSS/"
        },
        {
          "title": "JavaScript",
          "path": "/notes/JavaScript/"
        },
        {
          "title": "Vue",
          "path": "/notes/Vue/"
        },
        {
          "title": "Webpack",
          "path": "/notes/Webpack/"
        },
        {
          "title": "Node",
          "path": "/notes/Node/"
        }
      ],
      "/daysort/": [
        "/daysort/"
      ],
      "/interview/": [
        "/interview/"
      ],
      "/snippets/HTML/": [
        "/snippets/HTML/"
      ],
      "/snippets/CSS/": [
        "/snippets/CSS/"
      ],
      "/snippets/JavaScript/": [
        "/snippets/JavaScript/"
      ],
      "/snippets/Vue/": [
        "/snippets/Vue/"
      ],
      "/snippets/Node/": [
        "/snippets/Node/"
      ],
      "/snippets/WeChatApp/": [
        "/snippets/WeChatApp/"
      ]
    }
  }
}