/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "不甘当下",
  "description": "Vue,Vuepress",
  "base": "/lib/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/lib/img/avatar.png"
      }
    ],
    [
      "link",
      {
        "rel": "stylesheet",
        "href": "/lib/css/index.css"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/img/avatar.png",
        "heroText": "不甘当下",
        "tagline": "要一直学习,不想被淘汰",
        "actionText": "ENTER=>",
        "actionLink": "/zh/guide/",
        "footer": "MIT Licensed | Copyright © 2018-present"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-10f277a5",
      "path": "/"
    }
  ],
  "themeConfig": {
    "logo": "/img/avatar.png",
    "smoothScroll": true,
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端学习笔记",
        "link": "/guide/"
      },
      {
        "text": "代码片段",
        "ariaLabel": "Snippets",
        "items": [
          {
            "text": "Chinese",
            "link": "/language/chinese/"
          },
          {
            "text": "Japanese",
            "link": "/language/japanese/"
          }
        ]
      },
      {
        "text": "面试相关",
        "link": "https://goo11gle.com"
      },
      {
        "text": "个人博客",
        "link": "https://google.com"
      }
    ],
    "sidebarDepth": 1,
    "sidebar": [
      {
        "title": "Group 1",
        "path": "/foo/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          "/"
        ]
      },
      {
        "title": "Group 2",
        "children": [],
        "initialOpenGroupIndex": -1
      }
    ]
  }
}